define({
  root: {
    _widgetLabel: "Basemap Gallery",
    removeButton:"Remove",
    addButton:"Add as second basemap",
    setButton:"Set as only basemap",
	opacity:"Opacity: ",
	opacity2ndBasemap:"Opacity of the second basemap: "
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});